### ISSUE TITLE
Update common tree?

### ISSUE THREAD

**Issue by RealFX-Code** [Roynas-Android-Playground/vendor_samsung_a51#1]
The `device_samsung_universal9611-common` repo isn't available anymore and has been archived with the suffix `_old`.

Is there a reason behind this? Building Lineage21 is really difficult without an up-to-date common tree.

Thanks in advance.

**Comment by Royna2544** [comment]
can't read btw? old means old. Not updated

**Comment by RealFX-Code** [comment]
Hi, I was asking if you had an updated version that wasn’t uploaded. I can indeed read and that’s why i assume you have a new version somewhere else. Old implies the existence of a new.Regards, rlfx.On 1 Aug 2024, at 01:22, Soo-Hwan Na ***@***.***> wrote:﻿
can't read btw? old means old. Not updated
